services:
  db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  web:
    build: .
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/keepup
      - CHOKIDAR_USEPOLLING=true     # file watching on Windows/Mac
    depends_on:
      - db
    volumes:
      - .:/usr/src/app               # bind-mount your source
      - keepup_node_modules:/usr/src/app/node_modules   # <-- named volume
    command: ["npm","run","dev"]     # runs your dev script (uses nodemon)

volumes:
  dbdata:
  keepup_node_modules:   # <-- define the named volume
